# Generated by Django 3.1.2 on 2020-11-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Obj_type', models.CharField(max_length=100, verbose_name='type')),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(default='SOLD', max_length=100)),
                ('issues', models.CharField(default='No Issues', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
            ],
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
            ],
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.device')),
            ],
            bases=('inventory.device',),
        ),
    ]
