# Generated by Django 3.1.2 on 2020-11-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be sold'), ('SOLD', 'Item sold'), ('RESTOCING', 'Iten restocking in a few days')], default='SOLD', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be sold'), ('SOLD', 'Item sold'), ('RESTOCING', 'Iten restocking in a few days')], default='SOLD', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be sold'), ('SOLD', 'Item sold'), ('RESTOCING', 'Iten restocking in a few days')], default='SOLD', max_length=100),
        ),
    ]
