# Generated by Django 3.1.2 on 2020-11-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='Obj_type',
            new_name='type',
        ),
    ]
